import { Inter } from 'next/font/google'
import './globals.css'
import Header from './components/header'
import GLobalState from './context/store'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NexShop',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#f2f2f2" }}> 
        <GLobalState>
        <Header></Header>
         <main>{children}</main>       
         </GLobalState>
      </body>
    </html>
    
  )
}
